spring:
  datasource:
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 10000

logging:
  level:
    root: WARN
    com.mathenautics: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.flywaydb: INFO

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}